#!/bin/bash
set -uo pipefail

# Help command
usage() {
	echo "Usage: cprdirdir [flags] [quality]"
	echo "Trivial parallelization of cprdir. Opens up cprdir in all subdirectories."
	echo
	echo "Flags:"
	echo "	h - Displays help message"
	echo "	y - Force yes"
	echo "	v - Include video"
	echo "	f - Include fonts"
	echo "	c - Use more cores to compress (CPU hell)"
	echo "	l - Compress lossless"
	echo "	q - Specified quality"
	echo "	b - Do it in a backup"
	exit 1
}

# Argument parsing
yes=false
backup=false
do_vid=false
do_font=false
flags="-y"
while getopts ":hybvfcq:" opt; do
	case $opt in
		h) usage;;
		y) yes=true;;
		b) backup=true;;
		v) flags=$flags" -v";;
		f)
			if [[ -z "$(command -v fontconv)" ]]; then
				echo "Error: Dependency \"fontconv\" not found if you wish to compress fonts please refer to README.md.">&2
				usage
			else
				flags=$flags" -f"
			fi
			;;
		c) flags=$flags" -c";;
		l) flags=$flags" -l";;
		q)
			if [[ $OPTARG =~ ^[0-9]+$ ]]; then
				flags=$flags" -q $OPTARG"
			else
				echo "Error: Quality value is not a number, \"$OPTARG\".">&2
				usage
			fi
			;;
		\?) echo "Error: Unknown flag \"$OPTARG\"">&2; usage;;
		:)
			echo "Error: Quality flag set, but quality value not specified.">&2
			usage
			;;
	esac
done

# MAKING SURE
if ! $yes && ! $backup; then
	if ! do_vid; then
		echo "This will change images, and audio, found within:"
	else
		echo "This will change images, audio, and videos, found within:"
	fi
	echo "$(ls -d */)"
	read -p "Are you sure you wish to proceed (y/n): " input
	if [[ "$input" != "y" ]]; then
		exit 0
	fi
fi


# Kill in case
killProcs() {
	for pid in ${pids[*]}
	do
		kill $pid
	done
	return
}

# Checking for backup
dir_name="${PWD##*/}-compressed"
if $backup; then
	# Copy this directory into dir_name, we override already existing compressed dirs
	cp -r . "../$dir_name"
	cd "../$dir_name"
fi

# Starting cprs
i=0
pids=()
pid=""
goOn=true
# Cleanup
trap "killProcs" SIGTERM
while read dir
do
	# This will prompt us for each directory
	if [[ "${1-default}" == *"-"*"n"* ]]; then
		read -p "Do you want to compress $dir (y/n): " yesNo
		if ! [[ $yesNo == "y" ]]; then
			goOn=false
		fi
	fi
	# Checking if we're doing this directory
	if [[ $goOn == true ]]; then
		cd "${dir///}" # remove all instances of /
		cprdir $flags & pid=$!
		pids[${i}]=$pid
		i=$((i + 1))
		cd .. # Leave
	fi
done < <(ls -1 -d */ )


# Wait for all to be completed
for pid in ${pids[*]}
do
    wait $pid
done

echo "Finished Compressing"

exit
