#!/bin/bash
set -eo pipefail
IFS=$'\n\t'

# Usage
if [[ "$1" == *"-"*"h"* ]]; then
	echo "Usage: cprdir [flags] [quality #]"
	echo "File compression utility which uses FFMPEG to compress lots of files for you."
	echo
	echo "Flags:"
	echo "	h - Help"
	echo "	y - Force yes"
	echo "	b - Compress in a different directory (copies the entire directory over)"
	echo "	v - Include videos (videos take a while)"
	echo "	f - Include fonts (requires fontconv)"
	echo "	q - Check for Quality #"
	echo "		Quality #: Used by ffmpeg for images"
	echo "	c - Uses more cores to try and compress files more"
	echo
	echo "EX: cprdir -yqv 0"
	exit 1
fi

# Cancellation checks
# Do we have ffmpeg
if [[ -z "$(command -v ffmpeg)" ]]; then
	echo "Error: Missing dependency \"ffmpeg\"."
	exit 1
fi

# Ask the user if they really want to do this
if [[ "$1" != "-"*"y"*  && "$1" != "-"*"b"* ]]; then
	echo "This will change images, audio, and maybe videos, found within:"
	echo "	$(pwd)"
	read -p "Are you sure you wish to proceed (y/n): " input

	if [[ "$input" != "y" ]]; then
		echo "You can run this again with flag \"b\" to instead do all operations in a separate directory, thereby maintaining all of the original files."
		exit 0
	fi
fi

# Setting up temp directory name
tempdir="temp-compressing-$RANDOM"
dir_name="${PWD##*/}-compressed"

if [[ "$1" == "-"*"b"* ]]; then
	# Copy this directory into dir_name, we override already existing compressed dirs
	cp -r . "../$dir_name"
	cd "../$dir_name"
fi

# Cleanup
trap "rm -rf "$tempdir"" EXIT


# Setting up functions
# Find smallest value in tmp, or $f
min_tmp() {
	local min=$(stat -c%s "$f")
	local min_file=$f
	local size=0
	for temp_file in "$tempdir/"*
	do
		size=$(stat -c%s "$temp_file")
		if (( $size < $min )) && ! (( $size == 0 )) then
			min=$size
			min_file=$temp_file
		fi
	done

	# Returning minimum
	echo "$min_file"
}


# Parameter checks
qual=25
if [[ "$1" == "-"*"q"* ]]; then
	if [[ ! -z $2 ]]; then
		qual=$2
	else
		echo "Error: Quality flag set, but quality value not specified."
		exit 1
	fi
fi
do_vid=false
if [[ "$1" == "-"*"v"* ]]; then
	do_vid=true
fi
dont_core_max=true
if [[ "$1" == "-"*"c"* ]]; then
	dont_core_max=false
fi
do_font=false
if [[ "$1" == "-"*"f"* ]]; then
	if [[ -z "$(command -v fontconv)" ]]; then
		echo "Dependency \"fontconv\" not found if you wish to compress fonts please refer to README.md."
		echo "	Continuing without font compression."
	else
		do_font=true
	fi
fi

# Checking if we have an NVIDIA GPU for fast video compression
nvidia_gpu=false
if [[ ! -z "$(lspci | grep -i nvidia)" ]]; then
	nvidia_gpu=true
fi


# Starting script
mkdir "$tempdir"

find . -type f | while read f
do
	# Tracking variables
	cmpr=0 # Did we compress
	exp="" # What file format do we export it as
	mime_type="$(file --mime-type -b "$f")"

	# Compressing
	# Image Case
	if [[ "$mime_type" == "image/"* ]]; then
		# Current Winner: webp, qual 25, comp 4
		#	0 quality does COMPRESS, but you don't notice 25 quality
		if $dont_core_max; then
			ffmpeg -i "$f" -c:v libwebp -compression_level 4 -quality "$qual" "$tempdir/p1.webp" -loglevel error -y < /dev/null
		else
			ffmpeg -i "$f" -c:v libwebp -compression_level 4 -quality "$qual" "$tempdir/p1.webp" -loglevel error -y < /dev/null & PID1=$!
			ffmpeg -i "$f" -c:v libjxl -distance 6 -effort 7 "$tempdir/p2.jxl" -loglevel error -y < /dev/null & PID2=$!
			wait "$PID1"
			wait "$PID2"
		fi
		cmpr=1

	# Audio Case
	elif [[ "$mime_type" == "audio/"* ]]; then
		# Current winner: ogg, -c:a libopus -ab 32k -b:a 64k
		# libopus at lower bitrate sounds about the same as libvorbis, allows higher compression
		if $dont_core_max; then
			ffmpeg -i "$f" -c:a libopus -ab 32k -b:a 64k "$tempdir/a1.ogg" -loglevel error -y < /dev/null
		else
			ffmpeg -i "$f" -c:a libopus -ab 32k -b:a 64k "$tempdir/a1.ogg" -loglevel error -y < /dev/null & PID1=$!
			ffmpeg -i "$f" -c:a libvorbis -ab 32k -ar 22050 -b:a 96k "$tempdir/a2.ogg" -loglevel error -y < /dev/null & PID2=$!
			wait "$PID1"
			wait "$PID2"
		fi
		cmpr=1
	
	# Video Case
	elif $do_vid && [[ "$mime_type" == "video/"* ]]; then
		echo "Compressing Video: $f"
		if $nvidia_gpu; then
			ffmpeg -i "$f" -c:v av1_nvenc -preset p6 -rc vbr -cq 45 -c:a libopus -ab 32k -b:a 64k "$tempdir/v1.webm" -loglevel error -y < /dev/null
		else
			ffmpeg -i "$f" -c:v libvpx -b:v 1M -crf 45 -c:a libopus -ab 32k -b:a 64k "$tempdir/v1.webm" -loglevel error -y < /dev/null
		fi
		cmpr=1

	# Font Case
	# Scrict because fontconv is scrict
	elif $do_font && [[ "$f" == *".ttf" || "$f" == *".otf" ]]; then
		fontconv "$f" "$tempdir/f1.otf"
		cmpr=1
	fi

	# If we compressed and it's smaller replace
	if [[ $cmpr == 1 ]] then
		# Get the smallest file
		small_file=$(min_tmp)
		if [[ "$smallFile" != "$f" ]]; then
			echo "Compressed: $f	$(stat -c%s "$f") -> $(stat -c%s "$small_file")	($(basename "$small_file"))" # Print the file
			mv "$small_file" "$f"
		fi
		# Cleanup temp directory
		if [[ ! -z $(ls "$tempdir") ]]; then
			rm "$tempdir/"*
		fi
	fi
done

