#!/bin/bash

# No e since underlying cprdir can fail, and we dont want the main controlling cprdirdir to fail due to that
set -uo pipefail

# Help command
usage() {
	echo "Usage: cprdirdir [flags] [quality]"
	echo "Trivial parallelization of cprdir. Opens up cprdir in all subdirectories."
	echo
	echo "Flags:"
	echo "	h - Displays help message"
	echo "	y - Force yes"
	echo "	v - Include video"
	echo "	g - Use NVIDIA GPU for video compression"
	echo "	f - Include fonts (CURRENTLY DEACTIVATED LOOKING INTO NEW SOLUTION"
	echo "	c - Use more cores to compress (CPU hell)"
	echo "	l - Compress lossless"
    echo "	q - Specified quality (0 - 100, only for webp)"
	echo "	b - Do it in a backup"
	exit 1
}

# Argument parsing
yes=false
backup=false
do_vid=false
flags="-y"
while getopts ":hybvfglcq:" opt; do
	case $opt in
		h) usage;;
		y) yes=true;;
		b) backup=true;;
		v) flags=$flags" -v";;
		g) flags=$flags" -g";;
		f)
			echo "Error: Font compression is currently deactivated until better solution is found.">&2
			usage
			if [[ -z "$(command -v fontconv)" ]]; then
				echo "Error: Dependency \"fontconv\" not found if you wish to compress fonts please refer to README.md.">&2
				usage
			else
				flags=$flags" -f"
			fi
			;;
		c) flags=$flags" -c";;
		l) flags=$flags" -l";;
		q)
			if [[ $OPTARG =~ ^[0-9]+$ ]]; then
				flags=$flags" -q $OPTARG"
			else
				echo "Error: Quality value is not a number, \"$OPTARG\".">&2
				usage
			fi
			;;
		\?) echo "Error: Unknown flag \"$OPTARG\"">&2; usage;;
		:)
			echo "Error: Quality flag set, but quality value not specified.">&2
			usage
			;;
	esac
done

# MAKING SURE
if ! $yes && ! $backup; then
	if ! do_vid; then
		echo "This will change images, and audio, found within:"
	else
		echo "This will change images, audio, and videos, found within:"
	fi
	echo "$(ls -d */)"
	read -p "Are you sure you wish to proceed (y/n): " input
	if [[ "$input" != "y" ]]; then
		echo "Did not get a \"y\", exiting."
		usage
	fi
fi


# Kill in case
killProcs() {
	for pid in ${pids[*]}
	do
		kill $pid
	done
}

# Checking for backup
if $backup; then
	# Copy this directory into dir_name, we override already existing compressed dirs
	dir_name="${PWD##*/}-compressed"
	cp -rn . "../$dir_name"
	cd "../$dir_name"
fi

# Starting cprs
i=0
pids=()
pid=""
goOn=true
# Cleanup
trap "killProcs" SIGTERM
while read dir
do
	# Entering directory, and running cprdir
	cd "${dir///}" # remove all instances of /
	cprdir $flags & pid=$!
	pids[${i}]=$pid
	i=$((i + 1))
	cd .. # Leave
done < <(ls -1 -d */ )


# Wait for all to be completed
for pid in ${pids[*]}
do
    wait $pid
done

echo "Finished Compressing"

exit
