#!/bin/bash
set -uo pipefail

# Help command
if [[ "${1-default}" == *"-h"* ]]; then
	echo "Usage: cprdirdir [flags] [quality]"
	echo "Trivial parallelization of cprdir. Opens up cprdir in all subdirectories."
	echo
	echo "Flags:"
	echo "	h - Displays help message"
	echo "	y - Force yes"
	echo "	v - Include video"
	echo "	f - Include fonts"
	echo "	c - Use more cores to compress (CPU hell)"
	echo "	q - Specified quality"
	echo "	b - Do it in a backup"
	exit 1
fi

# MAKING SURE
if [[ "${1-default}" != *"-"*"y"* && "${1-default}" != *"-"*"b"* ]]; then
	if [[ "${1-default}" != *"-"*"v"* ]]; then
		echo "This will change images, and audio, found within:"
	else
		echo "This will change images, audio, and videos, found within:"
	fi
	echo "$(ls -d */)"
	read -p "Are you sure you wish to proceed (y/n): " input
	if [[ "$input" != "y" ]]; then
		exit 0
	fi
fi


# Kill in case
killProcs() {
	for pid in ${pids[*]}
	do
		kill $pid
	done
	return
}

# Checking for backup
dir_name="${PWD##*/}-compressed"
if [[ "$1" == "-"*"b"* ]]; then
	# Copy this directory into dir_name, we override already existing compressed dirs
	cp -r . "../$dir_name"
	cd "../$dir_name"
fi

# Managing flags
flags="-y"
if [[ "${1-default}" == *"-"*"v"* ]]; then
	flags=$flags"v"
fi
if [[ "${1-default}" == *"-"*"f"* ]]; then
	flags=$flags"f"
fi
if [[ "${1-default}" == *"-"*"c"* ]]; then
	flags=$flags"c"
fi
if [[ "${1-default}" == *"-"*"q"* ]]; then
	flags=$flags"q "$2 # If no 2 it should error
fi

# Starting cprs
i=0
pids=()
pid=""
goOn=true
# Cleanup
trap "killProcs" SIGTERM
while read dir
do
	# This will prompt us for each directory
	if [[ "${1-default}" == *"-"*"n"* ]]; then
		read -p "Do you want to compress $dir (y/n): " yesNo
		if ! [[ $yesNo == "y" ]]; then
			goOn=false
		fi
	fi
	# Checking if we're doing this directory
	if [[ $goOn == true ]]; then
		cd "${dir///}" # remove all instances of /
		cprdir $flags & pid=$!
		pids[${i}]=$pid
		i=$((i + 1))
		cd .. # Leave
	fi
done < <(ls -1 -d */ )


# Wait for all to be completed
for pid in ${pids[*]}
do
    wait $pid
done

echo "Finished Compressing"

exit
