#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# Usage
usage() {
	echo "Usage: cprdir [flags] [quality #]"
	echo "File compression utility which uses FFMPEG to compress lots of files for you."
	echo
	echo "Flags:"
	echo "	h - Help"
	echo "	y - Force yes"
	echo "	b - Compress in a different directory (copies the entire directory over)"
	echo "	v - Include videos (videos take a while)"
	echo "	g - Use NVIDIA GPU acceleration (video only) (lower quality, ~4-8x speedup on videos)"
	echo "	f - Include fonts (CURRENTLY REMOVED SINCE IT DOESN'T WORK ON LARGE FONTS)"
	echo "	c - Uses more cores to try and compress files more"
	echo "	l - For lossless"
	echo "	q - Check for Quality # (must be last flag)"
	echo "		Quality #: Used by ffmpeg for images (0 lowest, 100 highest)"
	echo
	echo "EX: cprdir -yvq 0"
	exit 1
}

# Cancellation checks
# Do we have ffmpeg
if [[ -z "$(command -v ffmpeg)" ]]; then
	echo "Error: Missing dependency \"ffmpeg\".">&2
	usage
fi

# Argument parsing
yes=false
backup=false
do_vid=false
do_font=false
dont_core_max=true
lossless=0
jxl_distance=7
use_gpu=false
qual=35
while getopts ":hybvgfclq:" opt; do
	case $opt in
		h) usage;;
		y) yes=true;;
		b) backup=true;;
		v) do_vid=true;;
		g) use_gpu=true;;
		c) dont_core_max=false;;
		l) lossless=1; jxl_distance=0;;
		f)
			echo "Error: Font compression is disabled until less buggy tool is found.">&2
			usage
			if [[ -z "$(command -v fontforge)" ]]; then
				echo "Error: Dependency \"fontforge\" not found if you wish to compress fonts please refer to README.md.">&2
				usage
			else
				do_font=true
			fi
			;;
		q)
			if [[ $OPTARG =~ ^[0-9]+$ ]]; then
				qual=$OPTARG
			else
				echo "Error: Quality value is not a number, \"$OPTARG\".">&2
				usage
			fi
			;;

		\?) echo "Error: Unknown flag \"$OPTARG\"">&2; usage;;
		:)
			echo "Error: Quality flag set, but quality value not specified.">&2
			usage
			;;
	esac
done


# Ask the user if they really want to do this
if ! $yes && ! $backup; then
	echo "This will change images, audio, and maybe videos, found within:"
	echo "	$PWD"
	read -p "Are you sure you wish to proceed (y/n): " input

	if [[ "$input" != "y" ]]; then
		echo "You can run this again with flag \"b\" to instead do all operations in a separate directory, thereby maintaining all of the original files."
		exit 0
	fi
fi

# Setting up temp directory name
tempdir="temp-compressing-$RANDOM"

if $backup; then
	# Copy this directory into dir_name, we override already existing compressed dirs
	dir_name="${PWD##*/}-compressed"
	cp -rn . "../$dir_name"
	cd "../$dir_name"
fi



# Checking if we have an NVIDIA GPU for fast video compression
# lspci is garunteed if we have NVIDIA, but there's not access everywhere, and you can have nvidia-smi but not have an nvidia GPU (it would be stupid which is why we are doing this approach)
nvidia_gpu=false
if $use_gpu && [[ ! -z "$(command -v nvidia-smi)" ]]; then
	nvidia_gpu=true
fi


# Making the temp directory for our compressed videos
mkdir "$tempdir"
trap "rm -rf "$tempdir"" EXIT # Cleanup

# Starting script
SECONDS=0

for f in $(find . -type f)
do
	# Tracking variables
	cmpr=0 # Did we compress
	exp="" # What file format do we export it as
	mime_type="$(file --mime-type -b "$f")"

	# Compressing
	# Image Case
	if [[ "$mime_type" == "image/"* ]]; then
		# Lossless Run
		if $dont_core_max && (( $lossless == 1 )); then
			ffmpeg -i "$f" -c:v libjxl -distance 0 -effort 6 "$tempdir/p1.jxl" -loglevel error -y
		# Normal Run
		elif $dont_core_max; then
			ffmpeg -i "$f" -c:v libwebp -compression_level 4 -quality "$qual" "$tempdir/p1.webp" -loglevel error -y
		# Trying Multiple Options Run
		else
			ffmpeg -i "$f" -c:v libwebp -lossless $lossless -compression_level 4 -quality "$qual" "$tempdir/p1.webp" -loglevel error -y & PID1=$!
			ffmpeg -i "$f" -c:v libjxl -distance $jxl_distance -effort 6 "$tempdir/p2.jxl" -loglevel error -y & PID2=$!
			wait "$PID1"
			wait "$PID2"
		fi
		cmpr=1

	# Audio Case
	elif [[ "$mime_type" == "audio/"* ]]; then
		# Current winner: ogg, -c:a libopus -ab 32k -b:a 64k
		# libopus at lower bitrate sounds about the same as libvorbis, allows higher compression
		echo "$f"
		# Lossless Run
		if (( $lossless == 1 )); then
			ffmpeg -i "$f" -c:a flac -compression_level 8 "$tempdir/a1.flac" -loglevel error -y
		# Normal Run
		elif $dont_core_max; then
			ffmpeg -i "$f" -c:a libopus -ab 32k -b:a 64k "$tempdir/a1.ogg" -loglevel error -y
		# Trying multiple options Run
		else
			ffmpeg -i "$f" -c:a libopus -ab 32k -b:a 64k "$tempdir/a1.ogg" -loglevel error -y & PID1=$!
			ffmpeg -i "$f" -c:a libvorbis -ab 32k -b:a 96k "$tempdir/a2.ogg" -loglevel error -y & PID2=$!
			wait "$PID1"
			wait "$PID2"
		fi
		cmpr=1
	
	# Video Case
	elif $do_vid && [[ "$mime_type" == "video/"* ]]; then
		echo "Compressing Video: $f"
		# Lossless Run
		if (( $lossless == 1 )); then
			ffmpeg -i "$f" -map 0 -c:v ffv1 -level 3 -g 1 -slicecrc 1 -slices 24 -coder 0 -context 0 -c:a flac -c:s copy "$tempdir/v1.mkv" -loglevel error -y
		# GPU Accelerated Run
		elif $nvidia_gpu; then
			ffmpeg -i "$f" -c:v av1_nvenc -preset p6 -tune hq -rc vbr -cq 50 -b:v 0 -multipass fullres -c:a libopus -ab 32k -b:a 64k "$tempdir/v1.mkv" -loglevel error -y
		# Normal Run
		else
			ffmpeg -i "$f" -c:v libsvtav1 -crf 50 -preset 6 -svtav1-params lp=4 -c:a libopus -ab 32k -b:a 64k "$tempdir/v1.mkv" -loglevel error -y 2> /dev/null
		fi
		cmpr=1

	# Font Case
	# Scrict because fontconv is scrict, otf is already lossless
	elif $do_font && [[ "$f" == *".ttf" || "$f" == *".otf" ]]; then
		# fontconv "$f" "$tempdir/f1.otf"
		# cmpr=1
		echo "Error: Somehow got to disabled font compression section.">&2
		exit 1
	fi

	# If we compressed and it's smaller replace
	if [[ $cmpr == 1 ]] then
		# Get the smallest file
		small_file=$(ls -Sr "$tempdir" | head -1)
		small_size=$(stat -c%s "$tempdir/$small_file")
		file_size=$(stat -c%s "$f")
		if (( small_size < file_size )); then
			echo "Compressed: $f	$file_size -> $small_size	($small_file)" # Print the file
			mv "$tempdir/$small_file" "$f"
		fi
		# Cleanup temp directory
		rm -f "$tempdir/"*
	fi
done

echo "$PWD took $SECONDS seconds."

